name: GitHub Pages Publish

on:
  push:
    branches: [main]

jobs:
  merge-main-with-deploy-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Merge to gh-deploy
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: gh-deploy
          github_token: ${{ secrets.GITHUB_TOKEN }}

  gh-deploy:
    runs-on: ubuntu-latest
    needs: merge-main-with-deploy-branch
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-deploy
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - run: yarn install
      - run: yarn build
      - name: Build
        run: yarn build:pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: "app/build"
