name: GitHub Pages Publish

on:
  push:
    branches: [rb-test-include]

jobs:
  gh-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - run: yarn install
      - name: Build
        working-directory: "sandbox"
        run: yarn build:pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: "sandbox/build"
